[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_BASE = "http://185.202.236.231:5000"
  REACT_APP_API_KEY = "83eb59e700efe317e71f754b81b921226739c6f5206cfc989705c08d12f45204"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"